package com.dev.org.export.decorator;

import com.dev.org.export.strategy.FileGeneratorStrategy;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.GZIPInputStream;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class CompressionDecoratorTest {

    @Mock
    private FileGeneratorStrategy decoratedGenerator;

    @Test
    @DisplayName("Should compress the content generated by the decorated generator")
    void shouldCompressContentGeneratedByDecoratedGenerator() throws IOException {
        // Given
        String testContent = "Test content for compression";
        ByteArrayResource originalResource = new ByteArrayResource(testContent.getBytes(StandardCharsets.UTF_8));
        
        when(decoratedGenerator.generate(any(), any())).thenReturn(originalResource);
        
        CompressionDecorator decorator = new CompressionDecorator(decoratedGenerator);
        
        String[] headers = {"Header1", "Header2"};
        List<Object[]> data = new ArrayList<>();
        data.add(new Object[]{"Value1", "Value2"});
        
        // When
        Resource compressedResource = decorator.generate(headers, data);
        
        // Then
        assertNotNull(compressedResource);
        
        // Verify the resource is compressed (GZIP)
        byte[] compressedBytes = compressedResource.getInputStream().readAllBytes();
        
        // Decompress and verify content
        try (GZIPInputStream gzipInputStream = new GZIPInputStream(new ByteArrayInputStream(compressedBytes))) {
            byte[] decompressedBytes = gzipInputStream.readAllBytes();
            String decompressedContent = new String(decompressedBytes, StandardCharsets.UTF_8);
            
            assertEquals(testContent, decompressedContent);
        }
        
        // Verify the decorated generator was called
        verify(decoratedGenerator).generate(headers, data);
    }

    @Test
    @DisplayName("Should append .gz extension to the filename")
    void shouldAppendGzExtensionToFilename() {
        // Given
        when(decoratedGenerator.getFilename("test")).thenReturn("test.csv");
        
        CompressionDecorator decorator = new CompressionDecorator(decoratedGenerator);
        
        // When
        String filename = decorator.getFilename("test");
        
        // Then
        assertEquals("test.csv.gz", filename);
        verify(decoratedGenerator).getFilename("test");
    }

    @Test
    @DisplayName("Should return application/gzip content type")
    void shouldReturnGzipContentType() {
        // Given
        CompressionDecorator decorator = new CompressionDecorator(decoratedGenerator);
        
        // When
        String contentType = decorator.getContentType();
        
        // Then
        assertEquals("application/gzip", contentType);
        // Content type should not delegate to decorated generator
        verifyNoInteractions(decoratedGenerator);
    }
}
